version: '3'
services:
  ee_service:
    build: ./ee_service
    command: rails s -b 0.0.0.0 -p 3003
    volumes:
      - ./ee_service/:/usr/src/ee_service
    ports:
      - 3003:3003
  events_service:
    build: ./events_service
    command: rails s -b 0.0.0.0 -p 3001
    volumes:
      - ./events_service/:/usr/src/events_service
    ports:
      - 3001:3001
  booking_service:
    build: ./booking_service
    command: rails s -b 0.0.0.0 -p 3000
    volumes:
      - ./booking_service/:/usr/src/booking_service
    ports:
      - "3000:3000"

